# Exercise the actual CLI executables with valid and invalid external data.
function(run expected)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT "${result}" STREQUAL "${expected}")
    message(FATAL_ERROR "Expected exit ${expected}, got ${result}: ${ARGN}\n${out}\n${err}")
  endif()
endfunction()

run(0 "${HELPER}" "${WORK}")
set(check "${CMAKE_COMMAND}" -E env GPUPRESOLVER_MAX_ITERS=0 "${CHECKER}")
run(0 ${check} "${WORK}/toy.mps" "${WORK}/valid")
run(1 ${check} "${WORK}/toy.mps" "${WORK}/infeasible")
foreach(case IN ITEMS nan inf long short)
  run(2 ${check} "${WORK}/toy.mps" "${WORK}/${case}")
endforeach()
run(2 ${check} "${WORK}/activity-overflow.mps" "${WORK}/overflow")
run(1 ${check} "${WORK}/large-bounds.mps" "${WORK}/large-infeasible")
run(0 ${check} "${WORK}/large-bounds.mps" "${WORK}/large-valid")
set(presolve "${CMAKE_COMMAND}" -E env GPUPRESOLVER_MAX_ITERS=10)
run(0 ${presolve} "${EXPORTER}" "${WORK}/precision.mps" "${WORK}/precision-export")
run(0 "${HELPER}" verify-export "${WORK}/precision-export" "${WORK}/precision.mps")
run(0 ${presolve} "${CHECKER}" "${WORK}/precision.mps" "${WORK}/empty")

if(EXISTS /dev/full)
  foreach(filename IN ITEMS c_f64.bin meta.txt)
    set(dir "${WORK}/full-${filename}")
    file(MAKE_DIRECTORY "${dir}")
    file(CREATE_LINK /dev/full "${dir}/${filename}" SYMBOLIC RESULT link_result)
    if(NOT "${link_result}" STREQUAL "0")
      message(FATAL_ERROR "Cannot prepare write-failure test: ${link_result}")
    endif()
    run(2 "${CMAKE_COMMAND}" -E env GPUPRESOLVER_MAX_ITERS=0
        "${EXPORTER}" "${WORK}/toy.mps" "${dir}")
  endforeach()
endif()
